name: axis
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.12.2


dependencies:
  flutter:
    sdk: flutter

 
  #UI
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.3.0
  cupertino_icons: ^1.0.8
  lottie: ^3.3.1
  shimmer: ^3.0.0
  fl_chart: ^1.2.0


  #Logic
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  get_it: ^9.2.1
  injectable: ^2.5.0
  dartz: ^0.10.1



  #Networking
  dio: ^5.9.2
  pretty_dio_logger: ^1.4.0


  #local storage
  shared_preferences: ^2.5.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #connectivity
  connectivity_plus: ^6.1.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2

  # Testing
  bloc_test: ^10.0.0
  mocktail: ^1.0.4



flutter:

  
  uses-material-design: true

  assets:
    - assets/icons/flags/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
